config/routes.rb
Rails.application.routes.draw do
  root to: 'matches#new'
  resources :matches, only: [:create, :new, :index, :show]
  resources :players, only: [:show, :index]
  resources :teams, only: [:show, :index]
  resources :leagues, only: [:show, :index]
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :league
  has_many :details
  has_many :players, through: :details
  has_many :teams, through: :players

  def teams
    match_teams = []
    self.players.each do |player|
        match_teams.push(player.team) unless match_teams.include?(player.team)
    end
    match_teams
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include MatchesHelper
  def new
  end

  def index
    @matches = Match.all.paginate(page: params[:page], per_page: 10)
  end

  def show
    @match = Match.find(params[:id])
    @factions = %w(radiant dire)
  end

  def create
    match_id = params[:match_id]
    @api = Dota.api
    @match = @api.matches(match_id.to_i)

    add_league(@match)
    add_teams(@match)
  end

  def find_league(league_id)
    @api.leagues.each do |league|
      return league if (league.id == league_id)
    end
  end

  def add_league(match)
    league = find_league(match.league_id)
    unless new_league = League.find_by_gcleague_id(match.league_id)
      new_league =  League.create(gcleague_id: match.league_id, name: league.name, description: league.description, url: league.url)
      add_matches(match, new_league.id)
    else
      add_matches(match, new_league.id)
    end
  end

  def add_matches(match, league_id)
    unless Match.find_by_gcmatch_id(match.id)
      new_match = Match.create(gcmatch_id: match.id, league_id: league_id, type_id: match.type_id, mode_id: match.mode_id, starts_at: match.starts_at, first_blood: match.first_blood, duration: match.duration, winner: match.winner,  positive_votes: match.positive_votes, negative_votes: match.negative_votes, players_count: match.players_count)
    end
  end

  def add_teams(match)
    valid_teams = [nil, nil] # Radiant first
    valid_teams[0] = match.radiant.id unless match.radiant.id.blank?
    valid_teams[1] = match.dire.id unless match.dire.id.blank?
    valid_teams.each_with_index do |gcteam_id, index|
      if gcteam_id.nil?
        new_team = Team.create(gcteam_id: gcteam_id, name: '-')
      else
        team = @api.teams(gcteam_id)
        new_team = Team.create(gcteam_id: gcteam_id, name: team.name, tag: team.tag, country_code: team.country_code, admin_id: team.admin_id, logo_id: team.logo_id, url: team.url, team_created: team.created_at) unless new_team = Team.find_by_gcteam_id(gcteam_id)
      end

      new_match = Match.find_by_gcmatch_id(match.id)
      index == 0 ? new_match.update_attributes(radiant_team: new_team.id) : new_match.update_attributes(dire_team: new_team.id)

      add_players(match, new_team, index) # radiant is 0
    end
  end

  def add_players(match, team, faction_index)
    faction_index == 0 ? faction = :radiant : faction = :dire
    match.send(faction).players.each do |player|
      unless new_player = Player.find_by_steam_32(player.id)
        new_player = Player.create(steam_32: player.id, steam_64: convert_to_64(player.id), steam_nickname: find_nickname(player.id), team_id: team.id)
        add_details(new_player.id, player, match, faction)
      else
        add_details(new_player.id, player, match, faction)
      end
    end
  end

  def add_details(player_id, player, match, faction)
    match_id = Match.find_by_gcmatch_id(match.id)
    kda = find_kda(player.kills, player.deaths, player.assists)
    Detail.create(player_id: player_id, match_id: match_id.id, hero_id: player.hero.id, faction: faction.to_s, slot: player.slot, item_1: player.items[0].id, item_2: player.items[1].id, item_3: player.items[2].id, item_4: player.items[3].id, item_5: player.items[4].id, item_6: player.items[5].id, level: player.level, kills: player.kills, deaths: player.deaths, assists: player.assists, last_hits: player.last_hits, denies: player.denies, kda: kda, gold: player.gold, gpm: player.gpm, xpm: player.xpm, status: player.status, gold_spent: player.gold_spent, hero_damage: player.hero_damage, tower_damage: player.tower_damage, hero_healing: player.hero_healing) unless Detail.find_by(match_id: match_id, player_id: player_id)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def winner(name)
    if name == :dire
      @match.dire.name
    else
      @match.radiant.name
    end
  end

  def find_nickname(id)
    SteamId.new(convert_to_64(id.to_i).to_i).nickname
  rescue
    'Unknown'
  end

  def avatar(id)
    SteamId.new(convert_to_64(id.to_i).to_i).full_avatar_url
  rescue
    ''
  end

  def custom_url(id)
    'http://steamcommunity.com/profiles/' + convert_to_64(id.to_i).to_s
    end

  def convert_to_64(id)
    '765' + (id + 61_197_960_265_728).to_s
  end

  def lobby_type(id)
    case id
    when -1
      'Invalid Lobby'
    when 0
      'Public Matchmaking'
    when 1
      'Practice'
    when 2
      'Tournament'
    when 3
      'Tutorial'
    when 4
      'Co-op with Bots'
    when 5
      'Team Match'
    when 6
      'Solo Queue'
    end
  end

  def game_mode(id)
    case id
    when 0
      'None'
    when 1
      'All Pick'
    when 2
      "Captain's Mode"
    when 3
      'Random Draft'
    when 4
      'Single Draft'
    when 5
      'All Random'
    when 6
      'Intro'
    when 7
      'Diretide'
    when 8
      "Reverse Captain's Mode"
    when 9
      'The Greeviling'
    when 10
      'Tutorial'
    when 11
      'Mid Only'
    when 12
      'Least Played'
    when 13
      'New Player Pool'
    when 14
      'Compendium Matchmaking'
    when 16
      'Captains Draft'
    end
  end

  def convert_to_mins(time)
    Time.at(time).utc.strftime('%H:%M:%S')
  end

  def find_team(id)
    if team = Team.find(id)
      return team.name
    else
      return 'Invalid Team'
    end
  end

  def find_winner_team(winner, match_id)
    if winner == 'radiant'
      Team.find(Match.find(match_id).radiant_team).name
    elsif winner == 'dire'
      Team.find(Match.find(match_id).dire_team).name
    end
  end

  def find_kda(k, d, a)
    k = k.to_f
    d = d.to_f
    a = a.to_f
    if d == 0.0
      return (k + a).round(1)
    else
      return ((k + a) / d).round(1)
    end
  end

  def players(match, faction)
    Match.find(match).details.where('faction = ?', faction)
  end

  def find_faction_team(faction, match)
    if faction == 'radiant'
      return "Radiant - #{find_team(match.radiant_team)}"
    elsif faction == 'dire'
      return "Dire - #{find_team(match.dire_team)}"
    end
  end

  def faction_color(faction)
    if faction == 'radiant'
      'green-text'
    elsif faction == 'dire'
        'red-text'
    end
  end
end

app/views/matches/_dire.html.haml
%h5.center Dire
.center.red-text.text-darken-2 #{@match.dire.name}
%ul.collection
  - @match.dire.players.each do |player|
    %li.collection-item
      = image_tag(avatar(player.id), class: 'avatar')
      = link_to(find_nickname(player.id), custom_url(player.id))

app/views/matches/_fab.html.haml
.fixed-action-btn{:style => "bottom: 45px; right: 24px;"}
  %a.btn-floating.btn-large.red.modal-trigger{href: "#modal1"}
    %i.large.material-icons add

app/views/matches/_match_details.html.haml
%h3.center #{@match.radiant.name} vs #{@match.dire.name}
%h5.center
  %span.red-text #{winner(@match.winner)}
  Victory !
%p.center Match Type: #{@match.type}
%p.center Match Mode: #{@match.mode}
%p.center Match Mode: #{@match.starts_at}

app/views/matches/_modal_match_id.html.haml
#modal1.modal
  .modal-content
    %h4.center Enter Match ID
    .row
      .col.s6.offset-s3
        .input-field
          %input#match_id.validate{:type => "number"}
          %label{:for => "match_id"} Match ID
        .center
          %a.waves-effect.waves-light.btn.red.lighten-2#submit Submit

app/views/matches/_preloader.html.haml
.center
  .preloader-wrapper.big.active
    .spinner-layer.spinner-blue-only
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle

app/views/matches/_radiant.html.haml
%h5.center Radiant
.center.green-text #{@match.radiant.name}
%ul.collection
  - @match.radiant.players.each do |player|
    %li.collection-item
      = image_tag(avatar(player.id), class: 'avatar')
      = link_to(find_nickname(player.id), custom_url(player.id))

app/views/matches/create.js.haml
:plain
  $('#match-details').html("#{escape_javascript(render 'match_details')}");
  $('#radiant').html("#{escape_javascript(render 'radiant')}");
  $('#dire').html("#{escape_javascript(render 'dire')}");

app/views/matches/index.html.haml
.card-panel
  %h5
    Match Count -
    = @matches.count
  %table.bordered.centered.responsive-table
    %thead
      %tr
        %th{'data-field': 'id'} ID
        %th{'data-field': 'id'} Type
        %th{'data-field': 'id'} Mode
        %th{'data-field': 'id'} Duration
        %th{'data-field': 'id'} Radiant
        %th{'data-field': 'id'} Dire
        %th{'data-field': 'id'} Winner
    %tbody
      - @matches.each do |match|
        %tr
          %td= link_to match.gcmatch_id, match
          %td= lobby_type(match.type_id)
          %td= game_mode(match.mode_id)
          %td= convert_to_mins(match.duration)
          %td= find_team(match.radiant_team)
          %td= find_team(match.dire_team)
          %td= find_winner_team(match.winner, match.id)
= will_paginate @matches,  renderer: MaterializePagination::Rails

app/views/matches/new.html.haml
= render 'fab'
= render 'modal_match_id'

.row
  .col.s12
    .card-panel.white#match-details
      %h4.center Match Details
.row
  .col.s6
    .card-panel.white#radiant
      %h5.center Radiant
  .col.s6
    .card-panel.white#dire
      %h5.center Dire

:coffeescript
  $('.modal-trigger').leanModal()
  $('#submit').on 'click', ->
    $('#modal1').closeModal()
    $('#match-details').html("#{escape_javascript(render 'preloader')}")
    $('#radiant').html("#{escape_javascript(render 'preloader')}")
    $('#dire').html("#{escape_javascript(render 'preloader')}")
    $.ajax
      url: '#{matches_path}'
      data: match_id: $('#match_id').val()
      type: 'POST'
    return

app/views/matches/show.html.haml
.card-panel
  %h5.center
    Match ID :
    = @match.gcmatch_id
  %h5.center
    League :
    = link_to @match.league.name, @match.league
  %h5.center{class: faction_color(@match.winner)}
    = find_winner_team(@match.winner, @match.id )
    Victory!
  - @factions.each do |faction|
    %h5{class: faction_color(faction)}= find_faction_team(faction, @match)
    %table.bordered
      %thead
        %tr
          %th{'data-field': 'id'} Player
          %th{'data-field': 'id'} Hero
          %th{'data-field': 'id'} Level
          %th{'data-field': 'id'} K
          %th{'data-field': 'id'} D
          %th{'data-field': 'id'} A
          %th{'data-field': 'id'} KDA
          %th{'data-field': 'id'} Gold
          %th{'data-field': 'id'} LH
          %th{'data-field': 'id'} DN
          %th{'data-field': 'id'} XPM
          %th{'data-field': 'id'} GPM
          %th{'data-field': 'id'} HD
          %th{'data-field': 'id'} HH
          %th{'data-field': 'id'} TD
          %th{'data-field': 'id'} Items
      %tbody
        - players(@match.id, faction).each do |detail|
          %tr
            %td= link_to Player.find(detail.player_id).steam_nickname, Player.find(detail.player_id)
            %td= find_hero(detail.hero_id)
            %td= detail.level
            %td= detail.kills
            %td= detail.deaths
            %td= detail.assists
            %td= find_kda(detail.kills, detail.deaths, detail.assists)
            %td= detail.gold
            %td= detail.last_hits
            %td= detail.denies
            %td= detail.xpm
            %td= detail.gpm
            %td= detail.hero_damage
            %td= detail.hero_healing
            %td= detail.tower_damage
            %td
              - find_item(detail.id).each do |item|
                = image_tag(item, class: "item-container")